#generated by AI and this is AI copy
#code version 1.0
#(c) 2026 BlueSnake open source code
import random

# ==========================================
# DUNGEONFALL
# ==========================================

player = {
    "name": "",
    "health": 100,
    "max_health": 100,
    "attack": 15,
    "defence": 5,
    "level": 1,
    "xp": 0,
    "gold": 20,
    "potions": 3
}

enemies = [
    {
        "name": "Goblin",
        "health": 40,
        "attack": 10,
        "defence": 2,
        "xp": 20,
        "gold": 10
    },
    {
        "name": "Skeleton",
        "health": 55,
        "attack": 13,
        "defence": 4,
        "xp": 30,
        "gold": 15
    },
    {
        "name": "Orc",
        "health": 75,
        "attack": 17,
        "defence": 6,
        "xp": 45,
        "gold": 25
    }
]

# Score statistics
score = 0
enemies_defeated = 0
rooms_completed = 0


# ==========================================
# INTRODUCTION
# ==========================================

print("=" * 45)
print("              DUNGEONFALL")
print("=" * 45)
print("        THE DUNGEON OF SHADOWS")
print("=" * 45)

player["name"] = input("Enter your character name: ")

print("\nWelcome,", player["name"] + "!")
print("Your adventure begins...")
print("Eight rooms stand between you and the")
print("terrifying Shadow King.")
print()


# ==========================================
# LEVEL-UP SYSTEM
# ==========================================

def check_level_up():

    required_xp = player["level"] * 50

    while player["xp"] >= required_xp:

        player["xp"] -= required_xp
        player["level"] += 1

        player["max_health"] += 20
        player["health"] = player["max_health"]

        player["attack"] += 4
        player["defence"] += 2

        print("\n" + "*" * 35)
        print("           LEVEL UP!")
        print("*" * 35)

        print("You are now level", player["level"])
        print("Maximum health increased!")
        print("Attack increased!")
        print("Defence increased!")
        print("Your health has been fully restored!")

        required_xp = player["level"] * 50


# ==========================================
# STATUS DISPLAY
# ==========================================

def show_status():

    print("\n---------- STATUS ----------")
    print("Name:", player["name"])
    print("Level:", player["level"])
    print(
        "Health:",
        player["health"],
        "/",
        player["max_health"]
    )
    print("Attack:", player["attack"])
    print("Defence:", player["defence"])
    print("XP:", player["xp"])
    print("Gold:", player["gold"])
    print("Potions:", player["potions"])
    print("Score:", score)
    print("----------------------------")


# ==========================================
# BATTLE SYSTEM
# ==========================================

def battle(enemy):

    global score
    global enemies_defeated

    print("\n" + "!" * 40)
    print("A", enemy["name"], "appears!")
    print("!" * 40)

    enemy_health = enemy["health"]

    while enemy_health > 0 and player["health"] > 0:

        print("\nYour health:", player["health"])
        print(
            enemy["name"],
            "health:",
            enemy_health
        )

        print("\n1. Attack")
        print("2. Heavy attack")
        print("3. Use potion")
        print("4. Run")

        choice = input("\nChoose an action: ")

        # ----------------------------------
        # NORMAL ATTACK
        # ----------------------------------

        if choice == "1":

            damage = random.randint(
                max(1, player["attack"] - 5),
                player["attack"] + 5
            )

            damage -= enemy["defence"]
            damage = max(1, damage)

            enemy_health -= damage

            print("\nYou dealt", damage, "damage!")

        # ----------------------------------
        # HEAVY ATTACK
        # ----------------------------------

        elif choice == "2":

            if random.random() < 0.65:

                damage = random.randint(
                    player["attack"],
                    player["attack"] * 2
                )

                damage -= enemy["defence"]
                damage = max(1, damage)

                enemy_health -= damage

                print("\nCRITICAL STRIKE!")
                print("You dealt", damage, "damage!")

            else:

                print("\nYour heavy attack missed!")

        # ----------------------------------
        # POTION
        # ----------------------------------

        elif choice == "3":

            if player["potions"] > 0:

                healing = random.randint(20, 35)

                player["health"] += healing

                if player["health"] > player["max_health"]:
                    player["health"] = player["max_health"]

                player["potions"] -= 1

                print("\nYou restored", healing, "health!")

            else:

                print("\nYou don't have any potions!")

            continue

        # ----------------------------------
        # RUN
        # ----------------------------------

        elif choice == "4":

            if random.random() < 0.5:

                print("\nYou successfully escaped!")

                return False

            else:

                print("\nYou failed to escape!")

        # ----------------------------------
        # INVALID INPUT
        # ----------------------------------

        else:

            print("\nInvalid choice.")
            continue

        # ----------------------------------
        # ENEMY ATTACK
        # ----------------------------------

        if enemy_health > 0:

            damage = random.randint(
                max(1, enemy["attack"] - 4),
                enemy["attack"] + 4
            )

            damage -= player["defence"]
            damage = max(1, damage)

            player["health"] -= damage

            print(
                enemy["name"],
                "dealt",
                damage,
                "damage!"
            )

    # ======================================
    # PLAYER DEFEATED
    # ======================================

    if player["health"] <= 0:

        player["health"] = 0

        print("\n" + "=" * 40)
        print("            YOU DIED")
        print("=" * 40)

        return False

    # ======================================
    # ENEMY DEFEATED
    # ======================================

    print("\n" + "-" * 40)
    print("You defeated the", enemy["name"] + "!")
    print("-" * 40)

    player["xp"] += enemy["xp"]
    player["gold"] += enemy["gold"]

    print("You gained", enemy["xp"], "XP!")
    print("You found", enemy["gold"], "gold!")

    # Score from defeating enemy
    points = enemy["xp"] * 10

    score += points
    enemies_defeated += 1

    print("Score earned:", points)

    check_level_up()

    return True


# ==========================================
# FINAL SCORE SYSTEM
# ==========================================

def final_score():

    global score

    print("\n")
    print("=" * 50)
    print("              DUNGEONFALL")
    print("             FINAL RESULTS")
    print("=" * 50)

    print("Player:", player["name"])
    print("Level reached:", player["level"])
    print("Rooms completed:", rooms_completed)
    print("Enemies defeated:", enemies_defeated)

    print("\nSCORE BREAKDOWN")
    print("-" * 50)

    print(
        "Combat and exploration score:",
        score
    )

    # Gold bonus
    gold_bonus = player["gold"] * 5

    # Health bonus
    health_bonus = max(0, player["health"]) * 2

    print("Gold bonus:", gold_bonus)
    print("Health bonus:", health_bonus)

    total_score = (
        score
        + gold_bonus
        + health_bonus
    )

    print("-" * 50)
    print("FINAL SCORE:", total_score)
    print("-" * 50)

    # ======================================
    # RANK SYSTEM
    # ======================================

    if total_score >= 5000:

        rank = "S - LEGENDARY"

    elif total_score >= 3500:

        rank = "A - MASTER"

    elif total_score >= 2000:

        rank = "B - WARRIOR"

    elif total_score >= 1000:

        rank = "C - ADVENTURER"

    elif total_score >= 500:

        rank = "D - BEGINNER"

    else:

        rank = "F - DEFEATED"

    print("FINAL RANK:", rank)

    print("=" * 50)


# ==========================================
# MAIN GAME
# ==========================================

rooms = 8

game_won = False

for room in range(1, rooms + 1):

    print("\n" + "=" * 45)
    print("ROOM", room, "OF", rooms)
    print("=" * 45)

    # ======================================
    # FINAL ROOM
    # ======================================

    if room == rooms:

        boss = {
            "name": "THE SHADOW KING",
            "health": 180,
            "attack": 25,
            "defence": 10,
            "xp": 150,
            "gold": 100
        }

        print("\nA terrifying presence fills the room...")
        print("The Shadow King has awakened!")

        survived = battle(boss)

        if not survived:

            print("\nGAME OVER!")
            break

        # Boss defeated
        print("\n" + "#" * 45)
        print("       YOU DEFEATED THE SHADOW KING!")
        print("#" * 45)

        rooms_completed += 1

        # Room completion bonus
        score += 100

        # Final boss bonus
        score += 2000

        print("\nRoom completion bonus: 100")
        print("Shadow King bonus: 2000")

        game_won = True

        show_status()

        break

    # ======================================
    # NORMAL ROOMS
    # ======================================

    event = random.randint(1, 4)

    # --------------------------------------
    # ENEMY
    # --------------------------------------

    if event == 1:

        enemy = random.choice(enemies).copy()

        survived = battle(enemy)

        if not survived:

            print("\nGAME OVER!")
            break

    # --------------------------------------
    # GOLD
    # --------------------------------------

    elif event == 2:

        gold_found = random.randint(10, 30)

        player["gold"] += gold_found

        print("\nYou found", gold_found, "gold!")

        score += gold_found * 2

        print(
            "Exploration score:",
            gold_found * 2
        )

    # --------------------------------------
    # POTION
    # --------------------------------------

    elif event == 3:

        player["potions"] += 1

        print("\nYou found a health potion!")

        score += 50

        print("Potion discovery bonus: 50")

    # --------------------------------------
    # HEALING FOUNTAIN
    # --------------------------------------

    else:

        healing = random.randint(5, 15)

        player["health"] += healing

        if player["health"] > player["max_health"]:

            player["health"] = player["max_health"]

        print("\nYou discovered a healing fountain!")

        print(
            "You restored",
            healing,
            "health."
        )

        score += 25

        print("Exploration bonus: 25")

    # ======================================
    # ROOM COMPLETION
    # ======================================

    rooms_completed += 1

    score += 100

    print("\nRoom completion bonus: 100")

    show_status()


# ==========================================
# GAME END
# ==========================================

if game_won:

    print("\nCongratulations!")
    print("You have conquered Dungeonfall!")

else:

    print("\nYour adventure has ended.")

# Always display final score
final_score()

print("\nThanks for playing DUNGEONFALL!")
print("Come back and try to beat your score!")
