#generated by AI and this is AI copy

# ============================================================
# TEACHER STUDENT REPORT GENERATOR
# ============================================================
#
# This program allows teachers to create student reports
# containing:
#
# - Student name
# - MEG (Minimum Expected Grade)
# - Predicted grade
# - Attitude to Learning
# - Homework
# - Teacher comments
#
# Replace the values marked [enter ...] with your own data.
# ============================================================


# ------------------------------------------------------------
# STUDENT DATA
# ------------------------------------------------------------
#
# Add as many students as you need.
#
# Example:
#
# {
#     "name": "[enter name]",
#     "meg": "[enter MEG]",
#     "predicted_grade": "[enter predicted grade]",
#     "attitude": "[enter attitude to learning]",
#     "homework": "[enter homework]",
#     "comment": "[enter teacher comment]"
# }
#
# ------------------------------------------------------------

students = [

    {
        "name": "[enter name]",
        "meg": "[enter MEG]",
        "predicted_grade": "[enter predicted grade]",
        "attitude": "[enter attitude to learning]",
        "homework": "[enter homework]",
        "comment": "[enter teacher comment]"
    },

    {
        "name": "[enter name]",
        "meg": "[enter MEG]",
        "predicted_grade": "[enter predicted grade]",
        "attitude": "[enter attitude to learning]",
        "homework": "[enter homework]",
        "comment": "[enter teacher comment]"
    },

    {
        "name": "[enter name]",
        "meg": "[enter MEG]",
        "predicted_grade": "[enter predicted grade]",
        "attitude": "[enter attitude to learning]",
        "homework": "[enter homework]",
        "comment": "[enter teacher comment]"
    },

    {
        "name": "[enter name]",
        "meg": "[enter MEG]",
        "predicted_grade": "[enter predicted grade]",
        "attitude": "[enter attitude to learning]",
        "homework": "[enter homework]",
        "comment": "[enter teacher comment]"
    },

    {
        "name": "[enter name]",
        "meg": "[enter MEG]",
        "predicted_grade": "[enter predicted grade]",
        "attitude": "[enter attitude to learning]",
        "homework": "[enter homework]",
        "comment": "[enter teacher comment]"
    },

    {
        "name": "[enter name]",
        "meg": "[enter MEG]",
        "predicted_grade": "[enter predicted grade]",
        "attitude": "[enter attitude to learning]",
        "homework": "[enter homework]",
        "comment": "[enter teacher comment]"
    },

    {
        "name": "[enter name]",
        "meg": "[enter MEG]",
        "predicted_grade": "[enter predicted grade]",
        "attitude": "[enter attitude to learning]",
        "homework": "[enter homework]",
        "comment": "[enter teacher comment]"
    },

    {
        "name": "[enter name]",
        "meg": "[enter MEG]",
        "predicted_grade": "[enter predicted grade]",
        "attitude": "[enter attitude to learning]",
        "homework": "[enter homework]",
        "comment": "[enter teacher comment]"
    }

]


# ------------------------------------------------------------
# DISPLAY A SINGLE REPORT
# ------------------------------------------------------------

def display_report(student):

    print("\n")
    print("=" * 60)
    print("                    STUDENT REPORT")
    print("=" * 60)

    print("Student:", student["name"])
    print()

    print("MEG:", student["meg"])
    print("Predicted Grade:", student["predicted_grade"])
    print("Attitude to Learning:", student["attitude"])
    print("Homework:", student["homework"])

    print()
    print("Teacher Comment:")
    print(student["comment"])

    print("=" * 60)


# ------------------------------------------------------------
# DISPLAY ALL REPORTS
# ------------------------------------------------------------

def display_all_reports():

    print("\n")
    print("=" * 60)
    print("                 ALL STUDENT REPORTS")
    print("=" * 60)

    for student in students:

        display_report(student)


# ------------------------------------------------------------
# FIND A STUDENT
# ------------------------------------------------------------

def find_student():

    name = input("\nEnter the student's name: ")

    found = False

    for student in students:

        if student["name"].lower() == name.lower():

            display_report(student)
            found = True
            break

    if not found:

        print("\nStudent not found.")


# ------------------------------------------------------------
# ADD A NEW STUDENT
# ------------------------------------------------------------

def add_student():

    print("\n")
    print("=" * 60)
    print("                 ADD NEW STUDENT")
    print("=" * 60)

    name = input("Student name: ")
    meg = input("MEG: ")
    predicted_grade = input("Predicted grade: ")
    attitude = input("Attitude to Learning: ")
    homework = input("Homework: ")
    comment = input("Teacher comment: ")

    new_student = {
        "name": name,
        "meg": meg,
        "predicted_grade": predicted_grade,
        "attitude": attitude,
        "homework": homework,
        "comment": comment
    }

    students.append(new_student)

    print("\nStudent successfully added.")


# ------------------------------------------------------------
# MAIN MENU
# ------------------------------------------------------------

def main():

    while True:

        print("\n")
        print("=" * 60)
        print("              TEACHER REPORT SYSTEM")
        print("=" * 60)

        print("1. View all reports")
        print("2. Find a student")
        print("3. Add a student")
        print("4. Exit")

        choice = input("\nSelect an option: ")

        if choice == "1":

            display_all_reports()

        elif choice == "2":

            find_student()

        elif choice == "3":

            add_student()

        elif choice == "4":

            print("\nExiting report system...")
            break

        else:

            print("\nInvalid option.")
            print("Please choose 1, 2, 3 or 4.")


# ------------------------------------------------------------
# START PROGRAM
# ------------------------------------------------------------

main()
